
services:
 postgresql:
    image: postgres:13-alpine
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nest-init
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

         